version: '3'
services:
  shio-nginx:
    container_name: shio-nginx
    image: nginx:1.13
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./containers/nginx/conf.d:/etc/nginx/conf.d
  shio-mariadb:
    container_name: shio-mariadb
    build: ./containers/mariadb
    restart: always    
    ports:
    - 3306:3306
    volumes:
    - ./volumes/mariadb/lib:/var/lib/mysql 
    environment:
      MYSQL_DATABASE: shio
      MYSQL_ROOT_PASSWORD: shio
      MYSQL_USER: shio
      MYSQL_PASSWORD: shio
  shio:
    container_name: shio
    build: .
    restart: always    
    ports:
     - 2710:2710
    volumes:
    - ./volumes/shio/store:/app/store   
    depends_on:
      - shio-nginx
      - shio-mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://shio-mariadb:3306/shio
      SPRING_DATASOURCE_USERNAME: shio
      SPRING_DATASOURCE_PASSWORD: shio
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect